import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { GlobalSidebar } from "@/components/common/global-sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <GlobalSidebar />
          <div className="flex flex-col w-100 flex-1">
            <header className="flex justify-around items-center h-fit bg-accent px-2 py-1">
              <SidebarTrigger />
              <span className="mx-auto">Logo</span>
            </header>
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
